name = 'emm'
license = 'MPL-2.0'
licenselink = 'https://github.com/mdavistffhrtporg/hugo-emm-theme/blob/main/LICENSE'
description = 'Development area for matthewd.org and matthewd.xyz'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mdavistffhrtporg/hugo-emm-theme'

# If you have a running demo of the theme
# demosite = 'https://matthewd.xyz/'

# Taxonomy terms
tags = ['blog', 'biography', 'minimal']
features = []

# If the theme has a single author
[author]
  name = 'Matthew A. Davis'
  homepage = 'https://matthewd.xyz/'
